# Generated by Django 2.1.9 on 2020-02-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='editor_typeid',
            field=models.IntegerField(choices=[(1, 'Organisation'), (2, 'Branch'), (3, 'RM'), (4, 'Others')], default=False),
        ),
    ]
