# Generated by Django 2.1.9 on 2020-02-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200225_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='editor_typeid',
            field=models.IntegerField(choices=[(1, 'Organisation'), (2, 'Branch')], default=False),
        ),
    ]
