# Generated by Django 2.1.9 on 2020-02-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200226_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='applicant',
            field=models.BooleanField(default=False),
        ),
    ]
