# Generated by Django 3.0.6 on 2020-08-12 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_applicant'),
        ('accounts', '0002_auto_20191031_0532'),
    ]

    operations = [
    ]
