# Generated by Django 2.1.9 on 2019-12-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0004_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='experience',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
