# Generated by Django 2.1.9 on 2020-03-04 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0002_shifttime'),
        ('attendee', '0005_employee_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='shifttime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hierarchy.Shifttime'),
        ),
    ]
