# Generated by Django 3.0.4 on 2020-04-22 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0006_shifttime_name'),
        ('attendee', '0007_employee_reporting_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Select branch', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hierarchy.Branch'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='doj',
            field=models.CharField(blank=True, help_text='Select joining date of employee', max_length=50, null=True),
        ),
    ]
