# Generated by Django 3.0.4 on 2020-04-22 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_designation_department'),
        ('attendee', '0008_auto_20200422_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='admin_for',
            field=models.IntegerField(blank=True, choices=[(1, 'Organisation'), (2, 'Branch'), (0, 'None')], help_text='Select and authorize an Employee ', null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Select Department for employee', null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.ForeignKey(blank=True, help_text='Select designation for employee', null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Designation'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, 'Male'), (0, 'Female')], help_text='Select gender of employee', null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'In-Active')], help_text='Select status of employee', null=True),
        ),
    ]
