# Generated by Django 3.0.6 on 2020-06-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0011_auto_20200609_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profilepic',
            field=models.FileField(blank=True, upload_to='media/documents/'),
        ),
    ]
