# Generated by Django 3.0.6 on 2020-06-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0012_auto_20200610_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profilepic',
            field=models.FileField(blank=True, upload_to='content/media/documents/'),
        ),
    ]
