# Generated by Django 3.0.6 on 2020-07-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0016_auto_20200702_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profilepic',
            field=models.FileField(blank=True, default='test.png', upload_to='profilepics/'),
        ),
    ]
