# Generated by Django 3.0.6 on 2020-07-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0018_auto_20200702_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profilepic',
            field=models.FileField(blank=True, upload_to='profilepics'),
        ),
    ]
