# Generated by Django 3.0.6 on 2020-07-03 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0021_auto_20200703_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profilepic',
            field=models.FileField(blank=True, upload_to='profilepics/'),
        ),
    ]
