# Generated by Django 3.0.6 on 2020-07-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0022_auto_20200703_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profilepic',
            field=models.FileField(blank=True, upload_to='content/media/profilepics/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='profilepic',
            field=models.FileField(blank=True, upload_to='content/media/documents/'),
        ),
    ]
