# Generated by Django 3.0.6 on 2020-07-03 11:15

import attendee.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0029_auto_20200703_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='pics',
            field=models.FileField(blank=True, upload_to=attendee.models.get_file_path),
        ),
    ]
