# Generated by Django 3.0.6 on 2020-07-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0030_auto_20200703_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emppics',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
