# Generated by Django 3.0.6 on 2020-07-18 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0031_employee_emppics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='emppics',
        ),
    ]
