# Generated by Django 3.0.6 on 2020-11-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0033_employee_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='probation_period',
            field=models.IntegerField(blank=True, default=0, help_text='allocate no. of day for probation period', null=True),
        ),
    ]
