# Generated by Django 2.1.9 on 2020-02-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayend', models.DateTimeField(unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
