# Generated by Django 2.1.9 on 2020-02-06 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_adate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adate',
            name='dayend',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
