# Generated by Django 2.1.9 on 2020-02-07 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20200206_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='fordate',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Date'),
        ),
    ]
