# Generated by Django 2.1.9 on 2020-03-12 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_auto_20200207_1053'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adate',
        ),
    ]
