# Generated by Django 3.0.4 on 2020-03-30 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_regularisation_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regularisation',
            name='user',
        ),
    ]
