# Generated by Django 3.0.4 on 2020-04-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_remove_regularisation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularisation',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Rejected')], null=True),
        ),
    ]
